[project]
name = "humidityd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "adafruit-circuitpython-dht>=4.0.10",
]

[tool.uv.workspace]
members = [
    "humidityd",
]
